version: '3.8'

services:
  app:
    image: javimosch/logovote
    expose:
      - "3000" # Map host port 3000 to container port 3000
    volumes:
      - data:/app/data # Mount the local ./data directory into /app/data in the container
volumes:
  data: